export const PIZZA_VEG_REQUEST = "PIZZA_VEG_REQUEST"
export const PIZZA_VEG_SUCCESS = "PIZZA_VEG_SUCCESS"
export const PIZZA_VEG_FAIL = "PIZZA_VEG_FAIL"
export const PIZZA_VEG_MODIFIED = "PIZZA_VEG_MODIFIED"

export const PIZZA_NONVEG_REQUEST = "PIZZA_NONVEG_REQUEST"
export const PIZZA_NONVEG_SUCCESS = "PIZZA_NONVEG_SUCCESS"
export const PIZZA_NONVEG_FAIL = "PIZZA_NONVEG_FAIL"
export const PIZZA_NONVEG_MODIFIED = "PIZZA_NONVEG_MODIFIED"

export const PIZZA_PIZZAMANIA_REQUEST = "PIZZA_PIZZAMANIA_REQUEST"
export const PIZZA_PIZZAMANIA_SUCCESS = "PIZZA_PIZZAMANIA_SUCCESS"
export const PIZZA_PIZZAMANIA_FAIL = "PIZZA_PIZZAMANIA_FAIL"

export const PIZZA_ALL_REQUEST = "PIZZA_ALL_REQUEST"
export const PIZZA_ALL_SUCCESS = "PIZZA_ALL_SUCCESS"
export const PIZZA_ALL_FAIL = "PIZZA_ALL_FAIL"

// pizza delete constants
export const PIZZA_DELETE_REQUEST = "PIZZA_DELETE_REQUEST"
export const PIZZA_DELETE_SUCCESS = "PIZZA_DELETE_SUCCESS"
export const PIZZA_DELETE_FAIL = "PIZZA_DELETE_FAIL"

// pizza create constants
export const PIZZA_CREATE_REQUEST = "PIZZA_CREATE_REQUEST"
export const PIZZA_CREATE_SUCCESS = "PIZZA_CREATE_SUCCESS"
export const PIZZA_CREATE_FAIL = "PIZZA_CREATE_FAIL"
export const PIZZA_CREATE_RESET = "PIZZA_CREATE_RESET"

// product details constants
export const PIZZA_DETAILS_REQUEST = "PIZZA_DETAILS_REQUEST"
export const PIZZA_DETAILS_SUCCESS = "PIZZA_DETAILS_SUCCESS"
export const PIZZA_DETAILS_FAIL = "PIZZA_DETAILS_FAIL"
export const PIZZA_DETAILS_RESET = "PIZZA_DETAILS_RESET"

// product update constants
export const PIZZA_UPDATE_REQUEST = "PIZZA_UPDATE_REQUEST"
export const PIZZA_UPDATE_SUCCESS = "PIZZA_UPDATE_SUCCESS"
export const PIZZA_UPDATE_FAIL = "PIZZA_UPDATE_FAIL"
export const PIZZA_UPDATE_RESET = "PIZZA_UPDATE_RESET"

export const CART_ADD_PIZZA = "CART_ADD_PIZZA"
export const CART_REMOVE_PIZZA = "CART_REMOVE_PIZZA"
export const CART_RESET = "CART_RESET"

// user login constants
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// user register constants
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// user profile constants
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL"
export const USER_PROFILE_RESET = "USER_PROFILE_RESET"

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST"
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS"
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL"
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET"

export const ADMIN_UPDATE_PROFILE_REQUEST = "ADMIN_UPDATE_PROFILE_REQUEST"
export const ADMIN_UPDATE_PROFILE_SUCCESS = "ADMIN_UPDATE_PROFILE_SUCCESS"
export const ADMIN_UPDATE_PROFILE_FAIL = "ADMIN_UPDATE_PROFILE_FAIL"

export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL"

export const USER_ORDER_LIST_REQUEST = "USER_ORDER_LIST_REQUEST"
export const USER_ORDER_LIST_SUCCESS = "USER_ORDER_LIST_SUCCESS"
export const USER_ORDER_LIST_FAIL = "USER_ORDER_LIST_FAIL"

// user delete constants
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

// order constants
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

// order list constants
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL"
export const ORDER_LIST_RESET = "ORDER_LIST_RESET"

// order details constants
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET"
